version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.6
    steps:
      - checkout
      - run: |
          set +e
          output=$(gem build *.gemspec)
          result=$?
          echo $output
          if [ $result -eq 0 ]; then
            SLACK_MESSAGE="Vagrant RubyGem built!"
          else
            SLACK_MESSAGE="Failed to build Vagrant RubyGem!"
            SLACK_STATE=$SLACK_ERROR
          fi
          eval $SLACK_EXECUTE
          exit $result
  build-website:
    # setting the working_directory along with the checkout path allows us to not have
    # to cd into the website/ directory for commands
    working_directory: ~/project/website
    docker:
      - image: hashicorp/middleman-hashicorp:0.3.35
    steps:
      - checkout:
          path: ~/project

      # restores gem cache
      - restore_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}

      - run:
          command: bundle check || bundle install --path vendor/bundle

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/website/vendor/bundle

      # middleman build
      - run:
          command: bundle exec middleman build

      # website deploy
      - run:
          command: ./scripts/deploy.sh

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: vagrant-test
  website:
    jobs:
      - build-website:
          context: static-sites
          filters:
            branches:
              only: stable-website
