version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.6
    steps:
      - checkout
      - run: |
          set +e
          output=$(gem build *.gemspec)
          result=$?
          echo $output
          SLACK_USERNAME=Vagrant
          SLACK_TITLE="Vagrant Builder"
          if [ $result -eq 0 ]; then
            SLACK_MESSAGE="Vagrant RubyGem built!"
          else
            SLACK_MESSAGE="Failed to build Vagrant RubyGem!"
            SLACK_STATE=$SLACK_ERROR
          fi
          eval $SLACK_EXECUTE
          exit $result
  release:
    docker:
      - image: circleci/ruby:2.4.6
    steps:
      - run: |
          set +e
          echo "TAG: ${CIRCLE_TAG}"
          curl -f -X POST -u "${HASHIBOT_USERNAME}:${HASHIBOT_TOKEN}" -H "Content-Type: application/json" -d "{\"tag_name\":\"${CIRCLE_TAG}\",\"target_commitish\":\"master\",\"name\":\"${CIRCLE_TAG}\"}" "https://api.github.com/repos/chrisroberts/vagrant-installers/releases"
          result=$?
          if [ $result -eq 0 ]; then
            SLACK_MESSAGE="Created new release on installers for tag: ${CIRCLE_TAG}"
          else
            SLACK_MESSAGE="Failed to create release on installers"
            SLACK_STATE="${SLACK_ERROR}"
          fi
          eval $SLACK_EXECUTE
          exit $result
  build-website:
    # setting the working_directory along with the checkout path allows us to not have
    # to cd into the website/ directory for commands
    working_directory: ~/project/website
    docker:
      - image: hashicorp/middleman-hashicorp:0.3.35
    steps:
      - checkout:
          path: ~/project

      # restores gem cache
      - restore_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}

      - run:
          command: bundle check || bundle install --path vendor/bundle

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/website/vendor/bundle

      # middleman build
      - run:
          command: bundle exec middleman build

      # website deploy
      - run:
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: vagrant-test
      - release:
          context: vagrant-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
  website:
    jobs:
      - build-website:
          context: static-sites
          filters:
            branches:
              only: stable-website
