version: 2
reference:
  environment: &ENVIRONMENT
    SLACK_USERNAME: Vagrant
    SLACK_TITLE: Vagrant CI
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.6
    steps:
      - checkout
      - run: |
          set +e
          output=$(gem build *.gemspec)
          result=$?
          echo $output

          SLACK_USERNAME=Vagrant
          SLACK_TITLE="Vagrant Builder"
          if [ $result -eq 0 ]; then
            SLACK_MESSAGE="Vagrant RubyGem built!"
          else
            SLACK_MESSAGE="Failed to build Vagrant RubyGem!"
            SLACK_STATE=$SLACK_ERROR
          fi
          eval $SLACK_EXECUTE
          exit $result
  release_build:
    docker:
      - image: circleci/ruby:2.4.6
    steps:
      - checkout
      - run: gem build *.gemspec
      - persist_to_workspace:
          root: .
          paths:
            - ./*.gem
  release_store:
    docker:
      - image: circleci/python:stretch
    steps:
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run: aws s3 cp ./vagrant-*.gem "${ASSETS_PRIVATE_BUCKET}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/"
  release:
    docker:
      - image: circleci/ruby:2.4.6
    environment:
      <<: *ENVIRONMENT
    steps:
      - run: |
          set +e
          echo "TAG: ${CIRCLE_TAG}"
          output=$(curl -s -S -f -X POST -u "${HASHIBOT_USERNAME}:${HASHIBOT_TOKEN}" -H "Content-Type: application/json" -d "{\"tag_name\":\"${CIRCLE_TAG}\",\"target_commitish\":\"master\",\"name\":\"${CIRCLE_TAG}\"}" "https://api.github.com/repos/chrisroberts/vagrant-installers/releases" 2>&1)
          result=$?
          if [ $result -eq 0 ]; then
            SLACK_MESSAGE="Created new release on installers for tag: ${CIRCLE_TAG}"
          else
            SLACK_MESSAGE="Failed to create release on installers\n\n```${output}```"
            SLACK_STATE="${SLACK_ERROR}"
          fi
          eval $SLACK_EXECUTE
          exit $result
  build-website:
    # setting the working_directory along with the checkout path allows us to not have
    # to cd into the website/ directory for commands
    working_directory: ~/project/website
    docker:
      - image: hashicorp/middleman-hashicorp:0.3.35
    steps:
      - checkout:
          path: ~/project

      # restores gem cache
      - restore_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}

      - run:
          command: bundle check || bundle install --path vendor/bundle

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: static-site-gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/project/website/vendor/bundle

      # middleman build
      - run:
          command: bundle exec middleman build

      # website deploy
      - run:
          command: ./scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: vagrant-test
          filters:
            branches:
              ignore: /.*/
      - release_build:
          context: vagrant-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release_store:
          context: vagrant-test
          requires:
            - release_build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release:
          context: vagrant-test
          requires:
            - release_store
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
  website:
    jobs:
      - build-website:
          context: static-sites
          filters:
            branches:
              only: stable-website
